<x-app-layout :title="'Formato 11 · Aula '.$formatoOnce->aula->numero">
    <x-slot name="header"><x-ui.page-header eyebrow="Documentación académica" title="Detalle del Formato 11" :description="'Aula '.$formatoOnce->aula->numero.' · '.($formatoOnce->aula->semestre?->nombre ?? 'Sin semestre').' · '.$formatoOnce->created_at->format('d/m/Y')" icon="heroicon-o-document-check"><x-slot name="actions"><a href="{{ route('profesor.formato-once.list', $formatoOnce->aula) }}" class="ui-btn-secondary">@svg('heroicon-o-arrow-left', 'h-4 w-4') Historial</a><a href="{{ route('profesor.formato-once.pdf', $formatoOnce) }}" class="ui-btn-secondary">@svg('heroicon-o-arrow-down-tray', 'h-4 w-4') PDF</a><a href="{{ route('profesor.formato-once.edit', $formatoOnce) }}" class="ui-btn-primary">@svg('heroicon-o-pencil', 'h-4 w-4') Editar</a></x-slot></x-ui.page-header></x-slot>
    <div class="ui-page">
        <div class="grid gap-4 sm:grid-cols-3"><x-ui.stat-card label="Estudiantes" :value="$formatoOnce->formatoOnceAlumnos->count()" description="Evaluados" icon="heroicon-o-user-group" /><x-ui.stat-card label="Conformes" :value="$formatoOnce->formatoOnceAlumnos->where('conformidad', true)->count()" description="Resultado favorable" icon="heroicon-o-check-circle" tone="success" /><x-ui.stat-card label="No conformes" :value="$formatoOnce->formatoOnceAlumnos->where('conformidad', false)->count()" description="Requieren atención" icon="heroicon-o-exclamation-triangle" tone="danger" /></div>
        <section class="ui-card overflow-hidden"><div class="ui-card-header"><x-ui.section-heading title="Evaluación por estudiante" :description="$formatoOnce->formatoOnceAlumnos->count().' registros del formato.'" icon="heroicon-o-table-cells" /></div><div class="overflow-x-auto"><table class="ui-table"><caption class="sr-only">Resultados del Formato 11</caption><thead><tr><th scope="col">Estudiante</th><th scope="col">Sede y ciclo</th><th scope="col">Competencias y capacidades</th><th scope="col">Actividad y producto</th><th scope="col">Resultado</th><th scope="col">Comentarios</th></tr></thead><tbody>
            @foreach($formatoOnce->formatoOnceAlumnos as $registro)<tr><td><p class="font-semibold text-gray-900">{{ $registro->alumno->nombre_completo }}</p><p class="mt-0.5 text-xs text-gray-500">{{ $registro->alumno->codigo_matricula }}</p></td><td><p class="font-medium text-gray-800">{{ $registro->sede_practicas ?: 'Sin sede' }}</p><p class="mt-1 text-xs text-gray-500">{{ $registro->ciclo_nivel ?: 'Sin ciclo' }}</p></td><td><p class="max-w-xs text-sm text-gray-700">{{ $registro->competencias ?: '—' }}</p><p class="mt-2 max-w-xs text-xs text-gray-500">{{ $registro->capacidades ?: 'Sin capacidades registradas' }}</p></td><td><p class="max-w-xs text-sm text-gray-700">{{ $registro->actividades ?: '—' }}</p><p class="mt-2 max-w-xs text-xs text-gray-500">Producto: {{ $registro->producto ?: '—' }}</p></td><td>@if($registro->conformidad)<span class="ui-badge-success">Conforme</span>@else<span class="ui-badge-danger">No conforme</span>@endif</td><td><p class="max-w-xs text-sm text-gray-700">{{ $registro->comentarios ?: 'Sin comentarios' }}</p></td></tr>@endforeach
        </tbody></table></div></section>
        @if($formatoOnce->firma_coordinador)<section class="ui-card"><div class="ui-card-header"><x-ui.section-heading title="Firma del coordinador" :description="$formatoOnce->created_at->format('d/m/Y H:i')" icon="heroicon-o-pencil-square" /></div><div class="ui-card-body"><div class="inline-block rounded-xl border border-gray-200 bg-white p-4"><img src="{{ asset('storage/'.$formatoOnce->firma_coordinador) }}" alt="Firma del coordinador" class="max-h-36 max-w-xs object-contain"></div></div></section>@endif
        <section class="rounded-xl border border-red-200 bg-red-50 p-5"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-red-900">Eliminar formato</h2><p class="mt-1 text-sm text-red-800">El registro y sus evaluaciones se eliminarán permanentemente.</p></div><form action="{{ route('profesor.formato-once.destroy', $formatoOnce) }}" method="POST" onsubmit="return confirm('¿Eliminar este formato? Esta acción no se puede deshacer.');">@csrf @method('DELETE')<button type="submit" class="ui-btn-danger">@svg('heroicon-o-trash', 'h-4 w-4') Eliminar</button></form></div></section>
    </div>
</x-app-layout>
