<x-app-layout :title="'Formato 12 · Aula '.$formato->aula->numero">
    <x-slot name="header"><x-ui.page-header eyebrow="Seguimiento de prácticas" title="Detalle del Formato 12" :description="'Aula '.$formato->aula->numero.' · '.($formato->aula->semestre?->nombre ?? 'Sin semestre').' · '.$formato->created_at->format('d/m/Y')" icon="heroicon-o-clipboard-document-check"><x-slot name="actions"><a href="{{ route('profesor.formato-doce.index') }}" class="ui-btn-secondary">@svg('heroicon-o-arrow-left', 'h-4 w-4') Historial</a></x-slot></x-ui.page-header></x-slot>
    <div class="ui-page">
        @php($alDia = $formato->formatosDoceAlumnos->where('al_dia', true)->count())
        <div class="grid gap-4 sm:grid-cols-3"><x-ui.stat-card label="Estudiantes" :value="$formato->formatosDoceAlumnos->count()" description="Monitoreados" icon="heroicon-o-user-group" /><x-ui.stat-card label="Al día" :value="$alDia" description="Avance esperado" icon="heroicon-o-check-circle" tone="success" /><x-ui.stat-card label="Con retraso" :value="$formato->formatosDoceAlumnos->count() - $alDia" description="Requieren seguimiento" icon="heroicon-o-exclamation-triangle" tone="danger" /></div>
        <section class="ui-card overflow-hidden"><div class="ui-card-header"><x-ui.section-heading title="Resultados del monitoreo" :description="$formato->formatosDoceAlumnos->count().' estudiantes registrados.'" icon="heroicon-o-table-cells" /></div><div class="overflow-x-auto"><table class="ui-table"><caption class="sr-only">Resultados del Formato 12</caption><thead><tr><th scope="col">Estudiante</th><th scope="col">Nivel</th><th scope="col">Sede</th><th scope="col">Responsable</th><th scope="col">Avance</th><th scope="col">Observaciones</th></tr></thead><tbody>
            @foreach($formato->formatosDoceAlumnos as $registro)<tr><td><p class="font-semibold text-gray-900">{{ $registro->alumno->nombre_completo }}</p><p class="mt-0.5 text-xs text-gray-500">{{ $registro->alumno->codigo_matricula }}</p></td><td><span class="ui-badge-info">{{ ucfirst($registro->nivel) }}</span></td><td><p class="max-w-xs text-sm text-gray-700">{{ $registro->sede_practica }}</p></td><td><p class="font-medium text-gray-800">{{ $registro->responsable }}</p><p class="mt-1 text-xs text-gray-500">{{ $registro->contacto_responsable }}</p></td><td>@if($registro->al_dia)<span class="ui-badge-success">Al día</span>@else<span class="ui-badge-danger">Con retraso</span>@endif</td><td><p class="max-w-xs text-sm text-gray-700">{{ $registro->observaciones ?: 'Sin observaciones' }}</p></td></tr>@endforeach
        </tbody></table></div></section>
        @if($formato->firma_coordinador)<section class="ui-card"><div class="ui-card-header"><x-ui.section-heading title="Firma del docente" :description="$formato->created_at->format('d/m/Y H:i')" icon="heroicon-o-pencil-square" /></div><div class="ui-card-body"><div class="inline-block rounded-xl border border-gray-200 bg-white p-4"><img src="{{ asset('storage/firmas/formato-12/'.$formato->firma_coordinador) }}" alt="Firma del docente responsable" class="max-h-36 max-w-xs object-contain"></div></div></section>@endif
        <section class="rounded-xl border border-red-200 bg-red-50 p-5"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-red-900">Eliminar formato</h2><p class="mt-1 text-sm text-red-800">El monitoreo consolidado se eliminará permanentemente.</p></div><form action="{{ route('profesor.formato-doce.destroy', $formato) }}" method="POST" onsubmit="return confirm('¿Eliminar este formato? Esta acción no se puede deshacer.');">@csrf @method('DELETE')<button type="submit" class="ui-btn-danger">@svg('heroicon-o-trash', 'h-4 w-4') Eliminar</button></form></div></section>
    </div>
</x-app-layout>
