<?php

return [
    'routes' => [
        'dashboard' => 'Resumen',
        'profile.edit' => 'Mi perfil',

        'login' => 'Iniciar sesión',
        'password.request' => 'Recuperar contraseña',
        'password.reset' => 'Restablecer contraseña',
        'password.confirm' => 'Confirmar contraseña',
        'verification.notice' => 'Verificar correo electrónico',
        'empresa.register.form' => 'Registro de empresa',
        'empresa.verify.form' => 'Verificar correo de empresa',

        'admin.aprobaciones.index' => 'Aprobación de empresas',
        'admin.aulas.index' => 'Gestión de aulas',
        'admin.aulas.create' => 'Crear aula',
        'admin.aulas.show' => 'Detalle del aula',
        'admin.aulas.agregar-alumnos' => 'Asignar estudiantes al aula',
        'admin.aulas.edit' => 'Editar aula',
        'admin.informes-finales.index' => 'Informes finales',
        'admin.perfil.empresa' => 'Perfil de empresa',
        'admin.perfil.solicitud' => 'Detalle de solicitud empresarial',
        'admin.usuarios.index' => 'Gestión de usuarios',
        'admin.usuarios.create' => 'Crear usuario',
        'admin.usuarios.show' => 'Detalle del usuario',
        'admin.usuarios.edit' => 'Editar usuario',

        'alumno.aula.index' => 'Mi aula',
        'alumno.cronograma.create' => 'Crear cronograma',
        'alumno.cronograma.show' => 'Mi cronograma',
        'alumno.entregas.create' => 'Registrar entrega',
        'alumno.entregas.show' => 'Detalle de entrega',
        'alumno.entregas.edit' => 'Editar entrega',
        'alumno.ficha.index' => 'Mi ficha de registro',
        'alumno.ficha.create' => 'Crear ficha de registro',
        'alumno.ficha.show' => 'Detalle de ficha de registro',
        'alumno.informe-final.index' => 'Mi informe final',
        'alumno.practicas.index' => 'Prácticas disponibles',
        'alumno.practicas.show' => 'Detalle de práctica',

        'empresa.postulaciones.index' => 'Postulaciones por publicación',
        'empresa.postulaciones.show' => 'Postulaciones recibidas',
        'empresa.publicaciones.index' => 'Mis publicaciones',
        'empresa.publicaciones.create' => 'Crear publicación',
        'empresa.publicaciones.edit' => 'Editar publicación',

        'profesor.aula.index' => 'Detalle del aula',
        'profesor.aulas.show' => 'Detalle del aula',
        'profesor.actividades.create' => 'Crear actividad',
        'profesor.actividades.show' => 'Detalle de actividad',
        'profesor.cronogramas.show' => 'Revisión de cronograma',
        'profesor.fichas.show' => 'Revisión de ficha de registro',
        'profesor.formato-once.index' => 'Formato 11',
        'profesor.formato-once.list' => 'Formatos 11 del aula',
        'profesor.formato-once.create' => 'Crear formato 11',
        'profesor.formato-once.show' => 'Detalle del formato 11',
        'profesor.formato-once.edit' => 'Editar formato 11',
        'profesor.formato-doce.index' => 'Formato 12',
        'profesor.formato-doce.create' => 'Crear formato 12',
        'profesor.formato-doce.show' => 'Detalle del formato 12',
        'profesor.informes-finales.index' => 'Informes finales de estudiantes',
        'profesor.monitoreos-practicas.index' => 'Monitoreo de prácticas',
        'profesor.monitoreos-practicas.show' => 'Detalle del monitoreo',
        'profesor.semanas.index' => 'Semanas académicas',
        'profesor.semanas.create' => 'Crear semana',
        'profesor.semanas.show' => 'Detalle de semana',
        'profesor.semanas.edit' => 'Editar semana',
    ],
];
