<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Semestre extends Model
{
    //
    protected $table = 'semestres';

    protected $fillable = [
        'nombre',
        'activo',
    ];

    protected static function booted()
    {
        // parent::booted(); // TODO: Change the autogenerated stub
        static::saving(function ($semestre) {

            // Si este semestre se activa
            if ($semestre->activo) {
                // Desactivar todos los demás
                static::where('id', '!=', $semestre->id)
                    ->update(['activo' => false]);
            }
        });
    }

    public function aulas(): HasMany
    {
        return $this->hasMany(Aula::class, 'semestre_id', 'id');
    }

    public function fichasRegistro()
    {
        return $this->hasMany(FichaRegistro::class, 'semestre_id');
    }
}
